/* BarometerStation: BMP085 temperature + plant/water controller (ESP32-WROOM).
   GPIO: BMP085/BH1750 SDA/SCL=21/22, soil=34, TDS=35, pump-driver=26,
   NeoPixel=25. Do not power the pump from the ESP32; share ground. */
#include <WiFi.h>
#include <WebServer.h>
#include <DNSServer.h>
#include <Preferences.h>
#include <Wire.h>
#include <PubSubClient.h>
#include <Adafruit_NeoPixel.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_BMP085.h>
#include <BH1750.h>
#include <ThingSpeak.h>
#include "secrets.h"

constexpr uint8_t SOIL_PIN=34, TDS_PIN=35, PUMP_PIN=26, PIXEL_PIN=25;
constexpr int MOISTURE_DRY_RAW=3000, MOISTURE_WET_RAW=1300; // Measure and replace after calibration.
constexpr uint32_t WIFI_CONNECT_TIMEOUT_MS=20000, SENSOR_INTERVAL_MS=2000;
constexpr uint32_t THINGSPEAK_INTERVAL_MS=20000, MQTT_INTERVAL_MS=30000, MAX_PUMP_MS=30000;
const char* AP_SSID="BarometerSetup"; const char* AP_PASS=""; const uint8_t AP_CHANNEL=6; IPAddress apIP(192,168,4,1);

struct Settings { bool autoWater=false; int moistureThreshold=35; uint32_t pumpMs=3000, led=0x008000; } settings;
Adafruit_BMP085 bmp; BH1750 lightMeter; bool sensorOK=false, lightSensorOK=false, inSetupPortal=false, pendingProvision=false, pumpOn=false;
float tempC=NAN, tdsPpm=NAN, lightLux=NAN; int soilRaw=0, soilPct=0;
Preferences prefs; String savedSsid,savedPass; bool provisioned=false; DNSServer dnsServer; WebServer server(80); WiFiClient netClient, thingSpeakClient; PubSubClient mqtt(netClient); Adafruit_NeoPixel pixel(1,PIXEL_PIN,NEO_GRB+NEO_KHZ800);
uint32_t lastSensorMs=0,lastThingSpeakMs=0,lastMqttMs=0,pumpStopAt=0;

int medianRead(uint8_t pin){ int v[15]; for(int &x:v){x=analogRead(pin);delay(2);} for(int i=0;i<14;i++)for(int j=i+1;j<15;j++)if(v[j]<v[i]){int t=v[i];v[i]=v[j];v[j]=t;} return v[7]; }
int toPercent(int raw){return constrain(map(raw,MOISTURE_DRY_RAW,MOISTURE_WET_RAW,0,100),0,100);}
void setLed(uint32_t c){settings.led=c&0xffffff;pixel.setPixelColor(0,pixel.Color((c>>16)&255,(c>>8)&255,c&255));pixel.show();}
void stopPump(){digitalWrite(PUMP_PIN,LOW);pumpOn=false;pumpStopAt=0;}
void startPump(uint32_t ms){digitalWrite(PUMP_PIN,HIGH);pumpOn=true;pumpStopAt=millis()+constrain(ms,1UL,MAX_PUMP_MS);}
void readSensors(){ if(sensorOK) tempC=bmp.readTemperature(); if(lightSensorOK) lightLux=lightMeter.readLightLevel(); soilRaw=medianRead(SOIL_PIN);soilPct=toPercent(soilRaw);float volts=medianRead(TDS_PIN)*3.3f/4095.0f;float t=isnan(tempC)?25.0f:tempC;float cv=volts/(1+0.02f*(t-25));tdsPpm=(133.42f*cv*cv*cv-255.86f*cv*cv+857.39f*cv)*0.5f; }
void loadPrefs(){prefs.begin("barometer",true);savedSsid=prefs.getString("ssid","");savedPass=prefs.getString("pass","");provisioned=prefs.getBool("prov",false);settings.autoWater=prefs.getBool("auto",false);settings.moistureThreshold=prefs.getInt("moisture",35);settings.pumpMs=prefs.getUInt("pumpMs",3000);settings.led=prefs.getUInt("led",0x008000);prefs.end();}
void saveSettings(){prefs.begin("barometer",false);prefs.putBool("auto",settings.autoWater);prefs.putInt("moisture",settings.moistureThreshold);prefs.putUInt("pumpMs",settings.pumpMs);prefs.putUInt("led",settings.led);prefs.end();}
bool connectToWiFi(const String &ssid,const String &pass){WiFi.persistent(false);WiFi.mode(WIFI_STA);WiFi.setAutoReconnect(true);WiFi.setSleep(false);WiFi.begin(ssid.c_str(),pass.c_str());uint32_t t=millis();while(WiFi.status()!=WL_CONNECTED&&millis()-t<WIFI_CONNECT_TIMEOUT_MS)delay(150);return WiFi.status()==WL_CONNECTED;}
String stateJson(){char out[320];snprintf(out,sizeof(out),"{\"ok\":%s,\"light_sensor_ok\":%s,\"temp\":%.2f,\"light_lux\":%.1f,\"soil_raw\":%d,\"soil_percent\":%d,\"tds_ppm\":%.1f,\"pump_on\":%s,\"auto_water\":%s,\"moisture_threshold\":%d,\"pump_ms\":%lu,\"led\":%lu}",sensorOK?"true":"false",lightSensorOK?"true":"false",tempC,lightLux,soilRaw,soilPct,tdsPpm,pumpOn?"true":"false",settings.autoWater?"true":"false",settings.moistureThreshold,(unsigned long)settings.pumpMs,(unsigned long)settings.led);return String(out);}
void mqttCallback(char* topic,byte* p,unsigned int n){String t(topic),v;for(unsigned i=0;i<n;i++)v+=(char)p[i];if(t.endsWith("/pump")){if(v=="OFF")stopPump();else startPump(v=="ON"?settings.pumpMs:v.toInt());}else if(t.endsWith("/auto_water")){settings.autoWater=(v=="ON"||v=="1");saveSettings();}else if(t.endsWith("/moisture_threshold")){settings.moistureThreshold=constrain(v.toInt(),0,100);saveSettings();}else if(t.endsWith("/led")){v.replace("#","");setLed(strtoul(v.c_str(),nullptr,16));saveSettings();}}
void ensureMqtt(){if(mqtt.connected()||WiFi.status()!=WL_CONNECTED)return;String id="barometer-"+String((uint32_t)ESP.getEfuseMac(),HEX);if(mqtt.connect(id.c_str(),MQTT_USERNAME,MQTT_PASSWORD)){String base=String(MQTT_BASE_TOPIC)+"/control/";mqtt.subscribe((base+"#").c_str());}}
void publish(){if(mqtt.connected()){String t=String(MQTT_BASE_TOPIC)+"/telemetry";mqtt.publish(t.c_str(),stateJson().c_str(),true);}}
void sendToThingSpeak(){if(WiFi.status()!=WL_CONNECTED||THING_SPEAK_CHANNEL==0)return;ThingSpeak.setField(1,tempC);ThingSpeak.setField(4,soilPct);ThingSpeak.setField(5,tdsPpm);ThingSpeak.setField(6,lightLux);ThingSpeak.writeFields(THING_SPEAK_CHANNEL,THING_SPEAK_WRITE_KEY);}

const char SETUP_HTML[] PROGMEM=R"HTML(<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><title>Setup</title><style>body{font:16px system-ui;max-width:25rem;margin:15vh auto;padding:1rem}input,button{display:block;width:100%;box-sizing:border-box;margin:.6rem 0;padding:.7rem}</style><h1>Barometer Station</h1><p>Connect this station to Wi-Fi.</p><form action=/save method=post><input name=ssid placeholder="Wi-Fi name" maxlength=32 required><input name=pass type=password placeholder="Password" maxlength=63 required><button>Connect</button></form>)HTML";
const char DASH_HTML[] PROGMEM=R"HTML(<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><title>Barometer Station</title><style>body{font:16px system-ui;max-width:46rem;margin:2rem auto;padding:0 1rem;background:#0f172a;color:#e2e8f0}.card{background:#1e293b;padding:1rem;border-radius:.7rem;margin:.8rem 0}input,button{font:inherit;margin:.25rem;padding:.35rem}label{display:block;margin:.4rem 0}.warn{color:#fca5a5}</style><h1>Barometer Station</h1><div class=card id=state>Loading…</div><div class=card><h2>Plant controls</h2><form action=/settings><label>Dry threshold % <input name=moisture type=number min=0 max=100></label><label>Maximum pump time (ms) <input name=pumpms type=number min=1 max=30000></label><label>NeoPixel <input name=led type=color></label><label><input name=auto type=checkbox> Water automatically when dry</label><button>Save</button></form><p><a href=/pump?state=on>Run pump</a> · <a href=/pump?state=off>Stop pump</a></p></div><p><button onclick="fetch('/reset-wifi')">Forget Wi-Fi</button></p><script>async function refresh(){let d=await (await fetch('/data')).json();state.innerHTML=`<b>${d.ok?'BMP085 online':'BMP085 not detected'} · ${d.light_sensor_ok?'BH1750 online':'BH1750 not detected'}</b><br>Local temperature: ${Number(d.temp).toFixed(1)} °C<br>Light: ${Number(d.light_lux).toFixed(0)} lx<br>Soil: ${d.soil_percent}% (raw ${d.soil_raw}) · TDS: ${Number(d.tds_ppm).toFixed(0)} ppm<br>Pump: ${d.pump_on?'ON':'OFF'}`;document.querySelector('[name=moisture]').value=d.moisture_threshold;document.querySelector('[name=pumpms]').value=d.pump_ms;document.querySelector('[name=auto]').checked=d.auto_water;document.querySelector('[name=led]').value='#'+Number(d.led).toString(16).padStart(6,'0')}refresh();setInterval(refresh,3000)</script>)HTML";
bool isIp(const String&s){for(size_t i=0;i<s.length();i++)if(s[i]!='.'&&(s[i]<'0'||s[i]>'9'))return false;return true;}
void handleRoot(){server.send_P(200,"text/html",inSetupPortal?SETUP_HTML:DASH_HTML);}
void handleSave(){String ssid=server.arg("ssid"),pass=server.arg("pass");if(ssid.isEmpty()||ssid.length()>32||pass.length()>63){server.send(400,"text/plain","Invalid Wi-Fi credentials");return;}prefs.begin("barometer",false);prefs.putString("ssid",ssid);prefs.putString("pass",pass);prefs.putBool("prov",true);prefs.end();savedSsid=ssid;savedPass=pass;provisioned=true;pendingProvision=true;server.send(200,"text/plain","Saved. Connecting…");}
void handleSettings(){if(server.hasArg("moisture"))settings.moistureThreshold=constrain(server.arg("moisture").toInt(),0,100);if(server.hasArg("pumpms"))settings.pumpMs=constrain((uint32_t)server.arg("pumpms").toInt(),1UL,MAX_PUMP_MS);if(server.hasArg("led")){String c=server.arg("led");c.replace("#","");setLed(strtoul(c.c_str(),nullptr,16));}settings.autoWater=server.hasArg("auto");saveSettings();server.sendHeader("Location","/");server.send(303);}
void registerRoutes(){server.on("/",HTTP_GET,handleRoot);server.on("/save",HTTP_POST,handleSave);server.on("/data",HTTP_GET,[]{server.send(200,"application/json",stateJson());});server.on("/settings",HTTP_GET,handleSettings);server.on("/pump",HTTP_GET,[]{server.arg("state")=="off"?stopPump():startPump(settings.pumpMs);server.sendHeader("Location","/");server.send(303);});server.on("/reset-wifi",HTTP_GET,[]{prefs.begin("barometer",false);prefs.clear();prefs.end();server.send(200,"text/plain","Wi-Fi forgotten; restarting.");delay(150);ESP.restart();});server.onNotFound([](){if(inSetupPortal&&!isIp(server.hostHeader())){server.sendHeader("Location",String("http://")+apIP.toString(),true);server.send(302,"text/plain","");}else server.send(404,"text/plain","Not found");});}
void startPortal(){inSetupPortal=true;WiFi.mode(WIFI_AP);WiFi.softAPConfig(apIP,apIP,IPAddress(255,255,255,0));WiFi.softAP(AP_SSID,strlen(AP_PASS)?AP_PASS:NULL,AP_CHANNEL);dnsServer.start(53,"*",apIP);server.begin();}
void stopPortal(){dnsServer.stop();WiFi.softAPdisconnect(true);inSetupPortal=false;}
void setup(){Serial.begin(115200);pinMode(PUMP_PIN,OUTPUT);stopPump();analogReadResolution(12);analogSetPinAttenuation(SOIL_PIN,ADC_11db);analogSetPinAttenuation(TDS_PIN,ADC_11db);Wire.begin(21,22);sensorOK=bmp.begin();lightSensorOK=lightMeter.begin(BH1750::CONTINUOUS_HIGH_RES_MODE,0x23,&Wire);prefs.begin("barometer",false);prefs.end();loadPrefs();pixel.begin();setLed(settings.led);ThingSpeak.begin(thingSpeakClient);mqtt.setServer(MQTT_HOST,MQTT_PORT);mqtt.setCallback(mqttCallback);registerRoutes();if(!provisioned||!connectToWiFi(savedSsid,savedPass))startPortal();else server.begin();}
void loop(){if(inSetupPortal){dnsServer.processNextRequest();server.handleClient();if(pendingProvision){stopPortal();loadPrefs();pendingProvision=false;if(connectToWiFi(savedSsid,savedPass))server.begin();else startPortal();}delay(5);return;}server.handleClient();ensureMqtt();mqtt.loop();uint32_t now=millis();if(pumpOn&&(int32_t)(now-pumpStopAt)>=0)stopPump();if(now-lastSensorMs>=SENSOR_INTERVAL_MS){lastSensorMs=now;if(!sensorOK)sensorOK=bmp.begin();readSensors();if(settings.autoWater&&!pumpOn&&soilPct<settings.moistureThreshold)startPump(settings.pumpMs);}if(now-lastThingSpeakMs>=THINGSPEAK_INTERVAL_MS){lastThingSpeakMs=now;sendToThingSpeak();}if(now-lastMqttMs>=MQTT_INTERVAL_MS){lastMqttMs=now;publish();}}
